name: KafkaMinecraft
version: 0.0.1
author: Stefan Cooper
main: com.stefancooper.KafkaMinecraft.Main
api-version: 1.14
website: https://stefancooper.com
commands:
  AddDoorbell:
    description: Add doorbell to coordinates to get motion notifications
    usage: /addDoorbell xCoordinate yCoordinate zCoordinate









